name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your node version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: CI=false npm run build  # Ensure this matches your build script
        env:
          REACT_APP_CUBE_API_URL: ${{ secrets.REACT_APP_CUBE_API_URL }}  # Pass the CUBE_API_URL from GitHub Secrets
          REACT_APP_CUBE_TOKEN: ${{ secrets.REACT_APP_CUBE_TOKEN }}  # Pass the CUBE_TOKEN from GitHub Secrets

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # This is the directory with the compiled app

    permissions:
        contents: write
